#!/bin/sh
winid=$1; shift
pipe="/tmp/surf.status.$winid"

if [ "$1" == "read" ]; then
	trap "rm $pipe" SIGINT SIGTERM
	tail -f $pipe | while read command param; do
		case $command in
			print) printf "$param"
				   ;;
			sleep) sleep "$param"
				   ;;
			exit)  break
				   ;;
		esac
	done
	rm $pipe
	exit 0
fi

if ! [ -p $pipe ]; then
	mkfifo $pipe
	( st -g 250x1 -w $winid -e $0 "$winid" read & )
fi

echo $@ | sed 's/\\n/\n/g' >> $pipe
